Improve logging when detecting errors when not being able to ping SM-DP+
ostelco/ostelco-core pull request #844
Opened 2019-09-24 09:37 UTC by la3lma

In our preprod-environment we have seen intermittent failures, but also that these failures do not report very well what's happening.  This patch adds more details to the error logs, and also cleans up a few minor issues elsewhere.

2019-09-25 13:08 UTC, vihangpatil requested changes

2019-09-25 13:08 UTC, vihangpatil commented on sim-administration/simmanager/src/main/kotlin/org/ostelco/simcards/profilevendors/ProfileVendorAdapterDatum.kt
> +                            return result.right()
This is a bug. Remove `return`.  Just `result.right()` should be kept.

2019-09-27 16:17 UTC, la3lma commented on sim-administration/simmanager/src/main/kotlin/org/ostelco/simcards/profilevendors/ProfileVendorAdapterDatum.kt
> +                            return result.right()
fixed

2019-09-27 23:53 UTC, vihangpatil approved these changes

2019-10-15 07:19 UTC, kmmatwork approved these changes

2019-10-16 09:28 UTC, merged