Synchronize client and server schema
ostelco/ostelco-core pull request #862
Opened 2019-10-08 19:17 UTC by havard024

2019-10-08 19:20 UTC, havard024 commented
@vihangpatil I think this fixes the issues between client / server schema.

2019-10-08 20:54 UTC, prasanthu requested changes
There are more `customer.graphqls` files in this project
```
 ~/dev/ostelco-core ‹develop› » find . | grep customer.graphqls
./graphql/src/test/resources/customer.graphqls
./prime/config/customer.graphqls
```

2019-10-09 07:29 UTC, havard024 commented
@prasanthu thanks for noticing! I've updated `./graphql/src/test/resources/customer.graphqls` in the previous commit

2019-10-09 09:25 UTC, prasanthu approved these changes

2019-10-09 10:48 UTC, closed without merging